version: '3'
services:
  py_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: py_app
    image: py_app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - HOST=localhost
      - PORT=8000

      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=test

    depends_on:
      - postgres

  postgres:
    image: postgres:13.3
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test